In [4]:
import torch

torch_elements = torch.tensor([5,2,8,9,11])

torch_elements[2]

tensor(8)

In [5]:
torch_elements[0]=22

In [7]:
torch_elements[3]=99

In [8]:
torch_elements

tensor([22,  2,  8, 99, 11])

In [10]:
import torch 
import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline  

In [11]:
torch.__version__

'2.9.1+cpu'

In [12]:
def plotVec(vectors):
    ax = plt.axes()
    
    # For loop to draw the vectors
    for vec in vectors:
        ax.arrow(0, 0, *vec["vector"], head_width = 0.05,color = vec["color"], head_length = 0.1)
        plt.text(*(vec["vector"] + 0.1), vec["name"])
    
    plt.ylim(-2,2)
    plt.xlim(-2,2)

In [13]:
ints_to_tensor = torch.tensor([0, 1, 2, 3, 4])
print("The dtype of tensor object after converting it to tensor: ", ints_to_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", ints_to_tensor.type())

The dtype of tensor object after converting it to tensor:  torch.int64
The type of tensor object after converting it to tensor:  torch.LongTensor


In [14]:
type(ints_to_tensor)

torch.Tensor

In [15]:
floats_to_tensor = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0])
print("The dtype of tensor object after converting it to tensor: ", floats_to_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", floats_to_tensor.type())

The dtype of tensor object after converting it to tensor:  torch.float32
The type of tensor object after converting it to tensor:  torch.FloatTensor


In [16]:
list_floats=[0.0, 1.0, 2.0, 3.0, 4.0]

floats_int_tensor=torch.tensor(list_floats,dtype=torch.int64)

In [17]:
print("The dtype of tensor object is: ", floats_int_tensor.dtype)
print("The type of tensor object is: ", floats_int_tensor.type())

The dtype of tensor object is:  torch.int64
The type of tensor object is:  torch.LongTensor


In [18]:
new_float_tensor = torch.FloatTensor([0, 1, 2, 3, 4])
new_float_tensor.type()
print("The type of the new_float_tensor:", new_float_tensor.type())

The type of the new_float_tensor: torch.FloatTensor


In [19]:
new_float_tensor = torch.FloatTensor([0, 1, 2, 3, 4])

In [20]:
old_int_tensor = torch.tensor([0, 1, 2, 3, 4])
new_float_tensor = old_int_tensor.type(torch.FloatTensor)
print("The type of the new_float_tensor:", new_float_tensor.type())

The type of the new_float_tensor: torch.FloatTensor


In [21]:
print("The size of the new_float_tensor: ", new_float_tensor.size())
print("The dimension of the new_float_tensor: ",new_float_tensor.ndimension())

The size of the new_float_tensor:  torch.Size([5])
The dimension of the new_float_tensor:  1


In [22]:
twoD_float_tensor = new_float_tensor.view(5, 1)
print("Original Size: ", new_float_tensor.size())
print("Size after view method", twoD_float_tensor.size())

Original Size:  torch.Size([5])
Size after view method torch.Size([5, 1])


In [23]:
twoD_float_tensor = new_float_tensor.view(-1, 1)
print("Original Size: ", new_float_tensor.size())
print("Size after view method", twoD_float_tensor.size())

Original Size:  torch.Size([5])
Size after view method torch.Size([5, 1])


In [26]:
numpy_array = np.array([0.1,1.0,2.0,3.0,4.0])
new_tensor = torch.from_numpy(numpy_array)
new_tensor
print(f'The data type of the new tensor: {new_tensor.dtype}')
print(f'The type of the new tensor: {new_tensor.type()}')

The data type of the new tensor: torch.float64
The type of the new tensor: torch.DoubleTensor


In [28]:
new_tensor
new_numpy_array = new_tensor.numpy()
new_numpy_array

array([0.1, 1. , 2. , 3. , 4. ])

In [34]:
numpy_array[:0]
print("The new tensor points to numpy_array : ", new_tensor)
print("and back to numpy array points to the tensor: ", new_numpy_array
)

The new tensor points to numpy_array :  tensor([0.1000, 1.0000, 2.0000, 3.0000, 4.0000], dtype=torch.float64)
and back to numpy array points to the tensor:  [0.1 1.  2.  3.  4. ]


In [38]:
# Convert a pandas series to a tensor

pandas_series = pd.Series([1.0,2.3,3.0,4.0])
new_tensor = torch.from_numpy(pandas_series.values)
new_tensor

tensor([1.0000, 2.3000, 3.0000, 4.0000], dtype=torch.float64)

In [41]:
this_tensor = torch.tensor([1.0,2.0,3.0,4.0])
this_tensor[2].item()

3.0

In [42]:
this_tensor[2]

tensor(3.)

In [43]:
this_tensor.tolist()

[1.0, 2.0, 3.0, 4.0]

In [46]:
your_tensor = torch.tensor([1,2,3,4,5])
your_tensor.view(5,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [47]:
tensor_sample = torch.tensor([20, 1, 2, 3, 4])
tensor_sample[0]=100
tensor_sample

tensor([100,   1,   2,   3,   4])

In [48]:
elements = range(0,20)

In [50]:
newelements = list(elements)

tensor_elements = torch.tensor(newelements)
tensor_elements

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [52]:
tensor_elements[0:8]

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
selected_index = [3,4]
tensor_elements[selected_index]

tensor([3, 4])

In [55]:
new_ele = [2,3,4,10,20,30,40]

new_tensor = torch.tensor(new_ele)

In [61]:
selected_index=[3,4]
new_tensor[selected_index]=3000

# new_tensor

In [63]:
practice_tensor = torch.tensor([2, 7, 3, 4, 6, 2, 3, 1, 2])

# Practice: Change the values on index 3, 4, 7 to 0

ind = [3,4,7]
practice_tensor[ind]=0
practice_tensor

tensor([2, 7, 3, 0, 0, 2, 3, 0, 2])

In [64]:
math_tensor = torch.tensor([1.0, -1.0, 1, -1])
print("Tensor example: ", math_tensor)

Tensor example:  tensor([ 1., -1.,  1., -1.])


In [66]:
mean = math_tensor.mean()
mean

tensor(0.)

In [68]:
max = math_tensor.max()
max

std = math_tensor.std()
std

tensor(1.1547)

In [69]:
pi_tensor = torch.tensor([0, np.pi/2, np.pi])
sin = torch.sin(pi_tensor)
print("The sin result of pi_tensor: ", sin)

The sin result of pi_tensor:  tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])


In [72]:
len_5_sensor = torch.linspace(0,10,steps=5)
len_5_sensor

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [73]:
pi_tensor = torch.linspace(0, 2*np.pi, 100)
sin_result = torch.sin(pi_tensor)

In [74]:
u=torch.tensor([1,2])
v=torch.tensor([0,1])
torch.dot(u, v)

tensor(2)

In [2]:
import torch
twoD_list = [[2,3,4],[4,5,6],[6,7,8]]
twoD_tensor = torch.tensor(twoD_list)
twoD_tensor

tensor([[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]])

In [8]:
twoD_tensor.ndimension()
twoD_tensor.shape
twoD_tensor.size()
twoD_tensor.numel()

9

In [9]:
twoD_numpy = twoD_tensor.numpy()
twoD_numpy

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
torch.from_numpy(twoD_numpy)

tensor([[2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]])

In [11]:
import pandas as pd 

df = pd.DataFrame({'a':[11,12,12],'b':[22,22,33]})
df.values

array([[11, 22],
       [12, 22],
       [12, 33]])

In [12]:
torch.tensor(df.values)

tensor([[11, 22],
        [12, 22],
        [12, 33]])

In [15]:
twoD_list[1][2]

6

In [17]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
tensor_example

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [23]:
tensor_example[1:3][1]

tensor([31, 32, 33])

In [25]:
tensor_example[2][1:3]

tensor([32, 33])

In [28]:
tensor_example[1:3,2]

tensor([23, 33])

In [33]:
tensor_example[1:3,2]

tensor([23, 33])

In [36]:
a=torch.tensor([[0,1,1],[1,0,1]])
a.ndimension()

2